--PL/SQL
--PL/SQL기본구성
DECLARE
    
BEGIN

EXCEPTION

END;
/

--화면에 출력하기
DECLARE

BEGIN

END;
/

DESC EMPLOYEES;

--%TYPE 와 SELECT 문을 활용하여 값을 가져오기
DECLARE
    VEMPLOYEE_ID EMPLOYEES.EMPLOYEE_ID%TYPE;
    VFIRST_NAME EMPLOYEES.FIRST_NAME%TYPE;
BEGIN
    SELECT EMPLOYEE_ID, FIRST_NAME INTO VEMPLOYEE_ID, VFIRST_NAME
    FROM EMPLOYEES
    WHERE FIRST_NAME = 'Susan';
    
    DBMS_OUTPUT.PUT_LINE('FIRST_NAME = '||VFIRST_NAME);
    DBMS_OUTPUT.PUT_LINE('EMPLOYEE_ID = '||VEMPLOYEE_ID);
END;
/

--EMPLOYEES에 해당 된 모든 이름, 직업, 사원번호를 출력 해 주는 프로그램을 작성하시오.
DECLARE
    --배열타입
    TYPE FIRST_NAME_ARRAY_TYPE IS TABLE OF EMPLOYEES.FIRST_NAME%TYPE INDEX BY BINARY_INTEGER;
    TYPE JOB_ID_ARRAY_TYPE IS TABLE OF EMPLOYEES.JOB_ID%TYPE INDEX BY BINARY_INTEGER;
    TYPE EMPLOYEE_ID_ARRAY_TYPE IS TABLE OF EMPLOYEES.EMPLOYEE_ID%TYPE INDEX BY BINARY_INTEGER;
    
    --배열타입 변수 선언
    FIRST_NAME_ARRAY FIRST_NAME_ARRAY_TYPE;
    JOB_ID_ARRAY JOB_ID_ARRAY_TYPE;
    EMPLOYEE_ID_ARRAY EMPLOYEE_ID_ARRAY_TYPE;
    ROW_ARRAY EMPLOYEES%ROWTYPE;    
    I BINARY_INTEGER := 0;
    J BINARY_INTEGER;
BEGIN
    --향상된 FOR문을 통해 RESULT SET값을 한개씩 가져와 각 컬럼 배열에 저장한다
    FOR ROW_ARRAY IN (SELECT * FROM EMPLOYEES)LOOP
        I := I+1;
        FIRST_NAME_ARRAY(I) := ROW_ARRAY.FIRST_NAME;
        JOB_ID_ARRAY(I) := ROW_ARRAY.JOB_ID;
        EMPLOYEE_ID_ARRAY(I) := ROW_ARRAY.EMPLOYEE_ID;
    END LOOP;
    --향상된 포문을 이용하여 컬럼 배열 값에 저장 된 값을 가져와서 출력 하시오.
    FOR J IN 1..I LOOP
        DBMS_OUTPUT.PUT_LINE(FIRST_NAME_ARRAY(J) || ' / ' || JOB_ID_ARRAY(J) || ' / ' || EMPLOYEE_ID_ARRAY(J));
    END LOOP;
END;
/