-- 트랜잭션
DROP TABLE DEP02;

--테이블 구조만 복사
CREATE TABLE DEP02
AS SELECT * FROM DEPARTMENTS
WHERE 1=0;

DESC DEP02;
SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'DEP02';
--내용복사
INSERT INTO DEP02 SELECT * FROM DEPARTMENTS;
--DEP02 테이블 확인
SELECT * FROM DEP02;
--커밋 전 내용 롤백
ROLLBACK;
--롤백테스트
DELETE FROM DEP02;
--세이브 포인트
SAVEPOINT C1;

DELETE FROM DEP02 WHERE DEPARTMENT_ID = 90;

--SAVEPOINT 까지 롤백
ROLLBACK TO C1;

--VIEW 생성하기
CREATE VIEW VIEW_EMP01
AS SELECT EMPLOYEE_ID, FIRST_NAME, SALARY, DEPARTMENT_ID
FROM EMP_COPY
WHERE DEPARTMENT_ID = 10;
--뷰 생성 확인
SELECT * FROM VIEW_EMP01;
--VIEW 수정하기
UPDATE VIEW_EMP01 SET SALARY = 4500 WHERE EMPLOYEE_ID = 200;


--EMPLOYEES를 복사해서 EMP_COPY 생성
CREATE TABLE EMP_COPY
AS 
SELECT * FROM EMPLOYEES;
--
SELECT * FROM EMP_COPY;
-- 뷰를 제거하기
DROP VIEW VIEW_EMP01;

SELECT * FROM USER_VIEWS;
SELECT * FROM USER_INDEXES;
SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'EMPLOYEES';

--가상뷰에 입력하기 (가상테이블에 컬럼4개 입력, 원본이 10개인데 그중에 NOT NULL이 존재, 가상테이블에 포함되어 있지 않다면?)
--즉 가상뷰 VIEW_EMP01 의 원본 EMPLOYEES의 속성중 NOT NULL이 존재하기 때문에 아래 방식으로는 입력 불가능
INSERT INTO VIEW_EMP01 VALUES (5,'MUN',4400,5);
--가상 테이블에 값을 입력하기 위해선 NOT NULL조건이 존재하는 속성을 전부 가져와야 입력가능
CREATE VIEW VIEW_EMP02
AS SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, HIRE_DATE, JOB_ID
FROM EMP_COPY
WHERE DEPARTMENT_ID = 10;

INSERT INTO VIEW_EMP02 VALUES (5,'JUNGBAE','MUN','123',TO_DATE('2021/12/24','YYYY/MM/DD'),'123');

SELECT * FROM VIEW_EMP02;

--
CREATE VIEW VIEW_EMP03
AS SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, HIRE_DATE, JOB_ID
FROM EMP_COPY;

INSERT INTO VIEW_EMP03 VALUES (5,'JUNGBAE','MUN','123',TO_DATE('2021/12/24','YYYY/MM/DD'),'123');

SELECT * FROM VIEW_EMP03 WHERE EMPLOYEE_ID = 5;
SELECT * FROM VIEW_EMP03;

SELECT * FROM EMP_COPY WHERE EMPLOYEE_ID = 5;
SELECT * FROM EMP_COPY;

--가상뷰에서 삭제 진행
DELETE FROM VIEW_EMP03 WHERE EMPLOYEE_ID = 5;