-- 트랜잭션
DROP TABLE DEP02;

--테이블 구조만 복사
CREATE TABLE DEP02
AS SELECT * FROM DEPARTMENTS
WHERE 1=0;

DESC DEP02;
SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'DEP02';
--내용복사
INSERT INTO DEP02 SELECT * FROM DEPARTMENTS;
--DEP02 테이블 확인
SELECT * FROM DEP02;
--커밋 전 내용 롤백
ROLLBACK;
--롤백테스트
DELETE FROM DEP02;
--세이브 포인트
SAVEPOINT C1;

DELETE FROM DEP02 WHERE DEPARTMENT_ID = 90;

--SAVEPOINT 까지 롤백
ROLLBACK TO C1;