--테이블 설계하기 (사원번호, 사원명, 급여)
-- CALSS EMP01 {
--    PUBLIC INT NUMBER;
--    PUBLIC STRING NAME;
--    PUBLIC INT SALARY;
-- }
CREATE TABLE EMP01(
--    EMPNO NUMBER(4) NOT NULL PRIMARY KEY,
--    ENAME VARCHAR2(20) NOT NULL UNIQUE,
--    SAL NUMBER(10, 2) NOT NULL
    EMPNO NUMBER(4),
    ENAME VARCHAR2(20) NOT NULL,
    SAL NUMBER(10, 2) DEFAULT 1000.0,
    CONSTRAINT EMP01_EMPNO_PK PRIMARY KEY(EMPNO), --기본키 지정
    CONSTRAINT EMP01_ENAME_UK UNIQUE(ENAME)
    )
    
INSERT INTO EMP01 VALUES(1001,'MUNJUNGBAE',2700.00);
    
SELECT ENAME FROM EMP01;
    
DELETE FROM EMP01 WHERE ENAME = 'MUNJUNGBAE'; 

SELECT * FROM EMPLOYEES;

SELECT * FROM EMPLOYEES
WHERE SALARY <= 10000 AND SALARY >= 5000;

SELECT * FROM EMPLOYEES
WHERE EMPLOYEE_ID IN(134, 201, 107);

SELECT EMPLOYEE_ID AS 직원번호, FIRST_NAME AS 이름, LAST_NAME AS 성, SALARY AS 급여
FROM EMPLOYEES
WHERE SALARY BETWEEN 2500 AND 4500;

SELECT EMPLOYEE_ID AS 직원번호, SALARY AS 급여 
FROM EMPLOYEES
WHERE LENGTH(FIRST_NAME) >= 6;

SELECT * FROM EMPLOYEES
WHERE HIRE_DATE LIKE '03/%%/%%';

SELECT * FROM EMPLOYEES
WHERE FIRST_NAME LIKE '%k';

SELECT FIRST_NAME
FROM EMPLOYEES
WHERE UPPER(SUBSTR(FIRST_NAME, LENGTH(FIRST_NAME),1)) = UPPER('k');

SELECT EMPLOYEE_ID, FIRST_NAME
FROM EMPLOYEES
WHERE FIRST_NAME NOT LIKE '%a%';

SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, JOB_ID 
FROM EMPLOYEES
WHERE MOD(EMPLOYEE_ID, 2) LIKE 0;

SELECT EMPLOYEE_ID, FIRST_NAME, SALARY, COMMISSION_PCT
FROM EMPLOYEES
WHERE COMMISSION_PCT IN(0.3, 0.05, 0.1);
    
SELECT EMPLOYEE_ID, FIRST_NAME, SALARY, COMMISSION_PCT
FROM EMPLOYEES
WHERE COMMISSION_PCT = 0.3 OR COMMISSION_PCT = 0.05 OR COMMISSION_PCT = 0.1;    

--현재시간 나타내기
SELECT TO_CHAR(SYSDATE,'YYYY/MM/DD HH24:MI:SS')
FROM DUAL;

SELECT TO_CHAR(SYSDATE,'DL')
FROM DUAL;

SELECT FLOOR(SYSDATE - TO_DATE('2024/11/05', 'YYYY/MM/DD'))
FROM DUAL;


--숫자를 우리가 원하는 방식으로 출력하기 EX) 1234567.23 => $1,234,567.23
SELECT TO_CHAR(1234567.23, 'L999,999,999.999')
FROM DUAL;