create or replace NONEDITIONABLE PROCEDURE EMP_PROC2
(VWORD IN VARCHAR2)
IS
    VEMP_ROWTYPE EMPLOYEES%ROWTYPE;
    CURSOR CURSOR_NAME(VWORD VARCHAR2)
    IS 
    SELECT * FROM EMPLOYEES WHERE UPPER(FIRST_NAME) LIKE UPPER('%'||VWORD||'%');
BEGIN
    FOR VEMP_ROWTYPE IN CURSOR_NAME(VWORD) LOOP
        DBMS_OUTPUT.PUT_LINE(VEMP_ROWTYPE.FIRST_NAME||' / '||VEMP_ROWTYPE.SALARY);
    END LOOP;
END;
/
--프로시저 출력
EXECUTE EMP_PROC2('U');

SHOW ERROR;

--SELECT * FROM USER_SOURCE;
--DATA DICTIONARY 명령어들
--USER_TABLES
--USER_CONSTRAINTS
--USER_CONS_COLUMNS
--USER_IND_COLUMNS
--USER_VIEWS
--USER_INDEXES
--USER_SEQUENCE
--USER_SOURCE