--테이블 설계하기 (사원번호, 사원명, 급여)
-- CALSS EMP01 {
--    PUBLIC INT NUMBER;
--    PUBLIC STRING NAME;
--    PUBLIC INT SALARY;
-- }
CREATE TABLE EMP01(
--    EMPNO NUMBER(4) NOT NULL PRIMARY KEY,
--    ENAME VARCHAR2(20) NOT NULL UNIQUE,
--    SAL NUMBER(10, 2) NOT NULL
    EMPNO NUMBER(4),
    ENAME VARCHAR2(20) NOT NULL,
    SAL NUMBER(10, 2) DEFAULT 1000.0,
    CONSTRAINT EMP01_EMPNO_PK PRIMARY KEY(EMPNO), --기본키 지정
    CONSTRAINT EMP01_ENAME_UK UNIQUE(ENAME)
    )
    
INSERT INTO EMP01 VALUES(1001,'MUNJUNGBAE',2700.00);
    
DROP TABLE EMP01;

SELECT * FROM EMP01;
    
DELETE FROM EMP01 WHERE ENAME = 'MUNJUNGBAE'; 

--내가 지금까지 만든 테이블 보여주기
SELECT * FROM TAB;

--테이블 내 개수 카운트
SELECT COUNT(*) FROM EMPLOYEES;

--테이블복사
CREATE TABLE EMPLE02
AS SELECT * FROM EMPLOYEES;

--테이블 내 내용 확인 (데이터 아님 주의);
DESC EMPLE02;

SELECT COUNT(*) FROM EMPLE02;

--제약조건 걸기
ALTER TABLE EMPLE02 ADD CONSTRAINT EMPLE02_ID_PK PRIMARY KEY(EMPLOYEE_ID);

ALTER TABLE EMPLE02 ADD CONSTRAINT EMPLE02_EMAIL_UK UNIQUE (EMAIL);

--제약조건 삭제
ALTER TABLE EMPLE02 DROP CONSTRAINT EMPLE02_EMAIL_UK;

--제약조건 보기
SELECT * 
FROM USER_CONSTRAINTS 
WHERE TABLE_NAME = UPPER('emple02');

SELECT TABLE_NAME, CONSTRAINT_TYPE
FROM USER_CONSTRAINTS 
WHERE TABLE_NAME = UPPER('EMPLE02');

--컬럼추가 => EMP01
ALTER TABLE EMP01 ADD JOB VARCHAR2(10) NOT NULL;

DESC EMP01;

--컬럼제거
ALTER TABLE EMP01 DROP COLUMN JOB;

--컬럼변경 (기존값이 존재 할 때 => 타입 변경 불가능.)
ALTER TABLE EMP01 MODIFY JOB NUMBER(10) DEFAULT 0;

--컬럼 이름 변경
ALTER TABLE EMP01 RENAME COLUMN JOB2 TO JOB;

--휴지통 보기
SELECT * FROM RECYCLEBIN;

--휴지통 복원
FLASHBACK TABLE EMP01 TO BEFORE DROP
RENAME TO EMP02;

--테이블 명 변경 EMP01 => EMP02
RENAME EMP02 TO EMP01;

DESC EMP01;

ALTER TABLE EMP01 MODIFY SAL NUMBER(10,2) NOT NULL;

--INSERT INTO
CREATE TABLE INSERT_TEST(
    NO1 NUMBER,
    NO2 NUMBER,
    NO3 NUMBER
    );
    
INSERT INTO INSERT_TEST VALUES(1,2,3);
SELECT * FROM IT;
RENAME INSERT_TEST TO IT;
INSERT INTO IT(NO1,NO2) VALUES(11,22);
INSERT INTO IT(NO1,NO2) VALUES(11,'문자');
INSERT INTO IT(NO1,NO2) VALUES(111); -- NO1,NO2 두개의 컬럼이있는데 2개여야 하기때문에 ㅇ 오류
INSERT INTO IT VALUES(111,NULL,333);
ALTER TABLE IT MODIFY NO3 NUMBER NOT NULL;

DELETE FROM IT WHERE NO3 IS NULL; --NO3의 NULL값 제거.

SELECT *
FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'IT';

--DEPT 테이블 생성
CREATE TABLE DEPT 
AS SELECT DEPARTMENT_ID, DEPARTMENT_NAME, LOCATION_ID
FROM DEPARTMENTS; 
SELECT * FROM DEPT;
TRUNCATE TABLE DEPT;
ROLLBACK;



INSERT INTO DEPT SELECT DEPARTMENT_ID, DEPARTMENT_NAME, LOCATION_ID
FROM DEPARTMENTS;








SELECT * FROM EMPLOYEES;

SELECT * FROM EMPLOYEES
WHERE SALARY <= 10000 AND SALARY >= 5000;

SELECT * FROM EMPLOYEES
WHERE EMPLOYEE_ID IN(134, 201, 107);

SELECT EMPLOYEE_ID AS 직원번호, FIRST_NAME AS 이름, LAST_NAME AS 성, SALARY AS 급여
FROM EMPLOYEES
WHERE SALARY BETWEEN 2500 AND 4500;

SELECT EMPLOYEE_ID AS 직원번호, SALARY AS 급여 
FROM EMPLOYEES
WHERE LENGTH(FIRST_NAME) >= 6;

SELECT * FROM EMPLOYEES
WHERE HIRE_DATE LIKE '03/%%/%%';

SELECT * FROM EMPLOYEES
WHERE FIRST_NAME LIKE '%k';

SELECT FIRST_NAME
FROM EMPLOYEES
WHERE UPPER(SUBSTR(FIRST_NAME, LENGTH(FIRST_NAME),1)) = UPPER('k');

SELECT EMPLOYEE_ID, FIRST_NAME
FROM EMPLOYEES
WHERE FIRST_NAME NOT LIKE '%a%';

SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, JOB_ID 
FROM EMPLOYEES
WHERE MOD(EMPLOYEE_ID, 2) LIKE 0;

SELECT EMPLOYEE_ID, FIRST_NAME, SALARY, COMMISSION_PCT
FROM EMPLOYEES
WHERE COMMISSION_PCT IN(0.3, 0.05, 0.1);
    
SELECT EMPLOYEE_ID, FIRST_NAME, SALARY, COMMISSION_PCT
FROM EMPLOYEES
WHERE COMMISSION_PCT = 0.3 OR COMMISSION_PCT = 0.05 OR COMMISSION_PCT = 0.1;    

--현재시간 나타내기
SELECT TO_CHAR(SYSDATE,'YYYY/MM/DD HH24:MI:SS')
FROM DUAL;

SELECT TO_CHAR(SYSDATE,'DL')
FROM DUAL;

SELECT FLOOR(SYSDATE - TO_DATE('2024/11/05', 'YYYY/MM/DD'))
FROM DUAL;


--숫자를 우리가 원하는 방식으로 출력하기 EX) 1234567.23 => $1,234,567.23
SELECT TRIM(TO_CHAR(1234567.23, 'L999,999,999.999')) AS MONEY
FROM DUAL;

SELECT FIRST_NAME, TRIM(TO_CHAR(SALARY, 'L999,999,999.999')) AS SALARY
FROM EMPLOYEES;

--문자 + 문자 = 숫자
SELECT TO_NUMBER('10,000', '999,999') + TO_NUMBER('20,000', '999,999') AS VALUE
FROM DUAL;

--NVL => 널값을 0으로 설정하기 위한 함수
SELECT FIRST_NAME, SALARY, NVL(COMMISSION_PCT,0) AS COMMISSION_PCT, JOB_ID
FROM EMPLOYEES
ORDER BY JOB_ID;

--NVL 일때
SELECT FIRST_NAME, SALARY,COMMISSION_PCT, SALARY+(SALARY*NVL(COMMISSION_PCT,0)) AS TOTAL
FROM EMPLOYEES;

--NVL2 일떄 => (대상, 널이 아닐때 적용 될 값, 널일 때 적용 될 값)
SELECT FIRST_NAME, SALARY,COMMISSION_PCT, SALARY+(SALARY*NVL2(COMMISSION_PCT, COMMISSION_PCT,0)) AS TOTAL
FROM EMPLOYEES;

CREATE TABLE CUSTOMER(
    CUSTOMER_CODE CHAR(7) NOT NULL,
    CUSTOMER_NAME VARCHAR2(10) NOT NULL,
    GENDER CHAR(1) NOT NULL,
    BIRTHDAY CHAR(8) NOT NULL,
    TEL VARCHAR2(16),
    EMAIL VARCHAR2(30),
    TOTAL_POINT NUMBER(10) DEFAULT 0
    );
    
ALTER TABLE CUSTOMER ADD CONSTRAINT CUSTOMER_CUSTOMER_CODE_PK PRIMARY KEY(CUSTOMER_CODE);
ALTER TABLE CUSTOMER ADD CONSTRAINT CUSTOMER_GENDER_CK CHECK(GENDER IN('M','W'));
ALTER TABLE CUSTOMER ADD CONSTRAINT CUSTOMER_EMAIL_UK UNIQUE(EMAIL);
    
DROP TABLE CUSTOMER;

SELECT *
FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'CUSTOMER';

SELECT TABLE_NAME, CONSTRAINT_TYPE
FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'CUSTOMER';

--학생 테이블을 만들어봅시다
CREATE TABLE STUDENT(
    STU_NUM NUMBER(5) NOT NULL,
    STU_NAME VARCHAR2(5) NOT NULL,
    KOR NUMBER(3) NOT NULL,
    ENG NUMBER(3) NOT NULL,
    MATH NUMBER(3) NOT NULL,
    SUM NUMBER(3) DEFAULT 0,
    AVG NUMBER(3) DEFAULT 0,
    SUB_CODE NUMBER(5) NOT NULL
    )
ALTER TABLE STUDENT ADD CONSTRAINT STUDENT_STU_NUM_PK PRIMARY KEY(STU_NUM);
ALTER TABLE STUDENT MODIFY STU_NAME VARCHAR2(20);
ALTER TABLE STUDENT MODIFY KOR NUMBER(5) DEFAULT 0;
ALTER TABLE STUDENT MODIFY ENG NUMBER(5) DEFAULT 0;
ALTER TABLE STUDENT MODIFY MATH NUMBER(5) DEFAULT 0;
ALTER TABLE STUDENT ADD CONSTRAINT STUDENT_SUB_CODE_FK FOREIGN KEY(SUB_CODE) REFERENCES SUBJECT(SUB_CODE);
    
--8. 학과 테이블
CREATE TABLE SUBJECT (
    SUB_CODE NUMBER(5) NOT NULL,
    SUB_NAME VARCHAR2(10) NOT NULL
    )   
ALTER TABLE SUBJECT ADD CONSTRAINT SUBJECT_SUB_CODE_PK PRIMARY KEY(SUB_CODE);
ALTER TABLE SUBJECT MODIFY SUB_NAME VARCHAR2(30);

SELECT * FROM STUDENT;
SELECT * FROM SUBJECT;

INSERT INTO STUDENT VALUES (1,'문정배',60,60,60,180,60,00011);
INSERT INTO SUBJECT VALUES (00011,'생명지구');

SELECT *
FROM USER_CONSTRAINTS
WHERE TABLE_NAME ='STUDENT';

SELECT *
FROM USER_CONSTRAINTS
WHERE TABLE_NAME ='SUBJECT';
