--studentHome
--테이블 생성
CREATE TABLE STU01 (
    NO NUMBER(4),
    NAME VARCHAR2(20),
    KOR NUMBER(4),
    ENG NUMBER(4),
    MATH NUMBER(4),
    SUM NUMBER(4) DEFAULT 0,
    AVG NUMBER(4,1) DEFAULT 0
);
ALTER TABLE STU01 ADD CONSTRAINT STU_NO_PK PRIMARY KEY(NO);

--시퀀스 생성
CREATE SEQUENCE STU_SEQ
START WITH 1
INCREMENT BY 1;

--합, 평균 구하는 트리거 생성
CREATE OR REPLACE TRIGGER STU_TRIGGER
BEFORE INSERT ON STU01
FOR EACH ROW
BEGIN
    :NEW.SUM := :NEW.KOR + :NEW.ENG + :NEW.MATH;
    :NEW.AVG := ROUND((:NEW.KOR + :NEW.ENG + :NEW.MATH) / 3, 1);
END;
/
--update 시 합, 평균이 같이 변하는 트리거 생성
CREATE OR REPLACE TRIGGER STU_TRIGGER2
BEFORE UPDATE ON STU01
FOR EACH ROW
BEGIN
    :NEW.SUM := :NEW.KOR + :NEW.ENG + :NEW.MATH;
    :NEW.AVG := ROUND((:NEW.KOR + :NEW.ENG + :NEW.MATH) / 3, 1);
END;


-- model view controller


--insert시 순위결정 트리거
CREATE OR REPLACE TRIGGER STU_TRIGGER3
BEFORE UPDATE ON STU01
FOR EACH ROW
BEGIN
    
END;
/

DROP TABLE STU01;
DROP SEQUENCE STU_SEQ;

INSERT INTO STU01(NO, NAME, KOR, ENG, MATH) VALUES(STU_SEQ.NEXTVAL, 'MUNJUNGBAE', 80, 85, 90);
INSERT INTO STU01(NO, NAME, KOR, ENG, MATH) VALUES(STU_SEQ.NEXTVAL, 'MUNJUNGBAE', 77, 23, 67);
COMMIT;
SELECT * FROM STU01;

SELECT NO, NAME, AVG, RANK() OVER(ORDER BY AVG DESC) AS RANK FROM STU01;

DELETE FROM STU01 WHERE NO = 1;

UPDATE STU01 SET KOR = 80, ENG = 90, MATH = 75 WHERE NO = 1;