--테이블 설계하기 (사원번호, 사원명, 급여)
-- CALSS EMP01 {
--    PUBLIC INT NUMBER;
--    PUBLIC STRING NAME;
--    PUBLIC INT SALARY;
-- }
CREATE TABLE EMP01(
--    EMPNO NUMBER(4) NOT NULL PRIMARY KEY,
--    ENAME VARCHAR2(20) NOT NULL UNIQUE,
--    SAL NUMBER(10, 2) NOT NULL
    EMPNO NUMBER(4),
    ENAME VARCHAR2(20) NOT NULL,
    SAL NUMBER(10, 2) DEFAULT 1000.0,
    CONSTRAINT EMP01_EMPNO_PK PRIMARY KEY(EMPNO), --기본키 지정
    CONSTRAINT EMP01_ENAME_UK UNIQUE(ENAME)
    )
    
INSERT INTO EMP01 VALUES ("0111","MUNJUNGBAE","2700.00");
    
DROP TABLE EMP01;
