--EMPLOYEES
SELECT * FROM EMPLOYEES;
DESC EMPLOYEES;

CREATE TABLE books (
    ID number(4),
    TITLE varchar2(50),
    PUBLISHER varchar2(30),
    YEAR varchar2(10),
    PRICE number(6)
);

ALTER TABLE BOOKS ADD CONSTRAINT BOOKS_ID_PK PRIMARY KEY(ID);

DESC BOOKS;



CREATE SEQUENCE BOOKS_ID_SEQ
START WITH 1
INCREMENT BY 1;

INSERT INTO books (ID, TITLE, PUBLISHER, YEAR, PRICE) VALUES (BOOKS_ID_SEQ.nextval, 'Operating System Concepts', 'Wiley', '2003',30700);
INSERT INTO books (ID, TITLE, PUBLISHER, YEAR, PRICE) VALUES (BOOKS_ID_SEQ.nextval, 'Head First PHP and MYSQL', 'OReilly', '2009', 58000);
INSERT INTO books (ID, TITLE, PUBLISHER, YEAR, PRICE) VALUES (BOOKS_ID_SEQ.nextval, 'C Programming Language', 'Prentice-Hall', '1989', 35000);
INSERT INTO books (ID, TITLE, PUBLISHER, YEAR, PRICE) VALUES (BOOKS_ID_SEQ.nextval, 'Head First SQL', 'OReilly', '2007', 43000);
commit;

SELECT * FROM BOOKS;
ROLLBACK;
DELETE FROM BOOKS WHERE ID = 5;

UPDATE BOOKS SET TITLE = 'KKK', PUBLISHER = 'JAVA', YEAR = '2024', PRICE = 33000 WHERE ID = 3;

drop table books;
DROP SEQUENCE BOOKS_ID_SEQ;

