--문제 풀이용 로컬 hr3

--1. 사원 번호와 사원명과 부서명과 부서의 위치를 출력하는 뷰(VIEW_LOC)를 작성하라.

CREATE OR REPLACE VIEW VIEW_LOC
AS
SELECT EMPLOYEE_ID, FIRST_NAME, DEPARTMENT_NAME, LOCATION_ID
FROM EMPLOYEES E INNER JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;

SELECT * FROM VIEW_LOC;
DROP VIEW VIEW_LOC;

--2. 30번 부서 소속 사원의 이름과 입사일과 부서명을 출력하는 뷰(VIEW_DEPT30)를 작성하라.
CREATE OR REPLACE VIEW VIEW_DEPT30
AS
SELECT E.DEPARTMENT_ID, FIRST_NAME, HIRE_DATE, DEPARTMENT_NAME
FROM EMPLOYEES E INNER JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
WHERE E.DEPARTMENT_ID LIKE 30;

SELECT * FROM VIEW_DEPT30;
DROP VIEW VIEW_DEPT30;
--3. 부서별 최대 급여 정보를 가지는 뷰(VIEW_DEPT_MAXSAL)를 생성하라.
CREATE OR REPLACE VIEW VIEW_DEPT_MAXSAL
AS
SELECT JOB_ID ,MAX(SALARY) AS "SALARY"
FROM EMPLOYEES 
GROUP BY JOB_ID;

SELECT * FROM VIEW_DEPT_MAXSAL;
DROP VIEW VIEW_DEPT_MAXSAL;

--4. 급여를 많이 받는 순서대로 3명만 출력하는 뷰(VIEW_SAL_TOP3)와 인라인 뷰로 작성하라.
SELECT ROWNUM, FIRST_NAME, SALARY
FROM (SELECT FIRST_NAME, SALARY
      FROM EMPLOYEES
      ORDER BY SALARY DESC)
      WHERE ROWNUM < 4;

