--자바에서 CallableStatement

DROP TABLE EMP1;

SELECT * FROM EMP1 ORDER BY DEPARTMENT_ID;

CREATE TABLE EMP1
AS
SELECT EMPLOYEE_ID, FIRST_NAME, DEPARTMENT_ID, SALARY FROM EMPLOYEES;

--부서코드가 10이면 10%, 20이면 20%, 나머지는 동결하는 프로시저
CREATE OR REPLACE PROCEDURE EMP1_PROC(
    VDEPARTMENT_ID IN EMP1.DEPARTMENT_ID%TYPE,
    VINCREMENT NUMBER
)
IS
    VINCREMENT_SALARY NUMBER;
BEGIN
    VINCREMENT_SALARY := VINCREMENT / 100;
    UPDATE EMP1 
    SET SALARY = SALARY + SALARY * VINCREMENT_SALARY
    WHERE DEPARTMENT_ID = VDEPARTMENT_ID;
    
END;
/

CREATE OR REPLACE PROCEDURE BOOKS_PROC(
    VID IN BOOKS.ID%TYPE,
    VPRICE IN BOOKS.PRICE%TYPE,
    VMESSAGE OUT VARCHAR2
)
IS 
    VBOOKS_RT BOOKS%ROWTYPE;
BEGIN
    UPDATE BOOKS
    SET PRICE = PRICE + VPRICE WHERE ID = VID;
    COMMIT;
              
    SELECT * INTO VBOOKS_RT FROM BOOKS WHERE ID = VID;
    VMESSAGE := VBOOKS_RT.ID|| '번호의' || ' 인상 금액은 ' || VPRICE || '원 으로 총 ' || VBOOKS_RT.PRICE ||'원 입니다.'; 
END;
/

commit;

EXECUTE EMP1_PROC(10);
EXECUTE EMP1_PROC(20);
EXECUTE EMP1_PROC(30);
DROP PROCEDURE EMP1_PROC;
ROLLBACK;


VARIABLE MESSAGE VARCHAR2(500);
EXECUTE BOOKS_PROC(1, 10000, :MESSAGE);
SELECT * FROM BOOKS;