CREATE TABLE STUDENT2(
	NO NUMBER(4), --PK
	NAME VARCHAR2(20) NOT NULL,
	YEAR VARCHAR2(20) NOT NULL,
	GRADE NUMBER(3,2) NOT NULL,
	BIRTH VARCHAR2(20) NOT NULL,
	PHONE VARCHAR2(20) NOT NULL,
	MNUM VARCHAR2(10) --FK
);
ALTER TABLE STUDENT2 ADD CONSTRAINT SD_NO_PK PRIMARY KEY(NO);
ALTER TABLE STUDENT2 ADD CONSTRAINT SD_MJ_NUM_FK FOREIGN KEY(MNUM) REFERENCES MAJOR(MNUM) ON DELETE SET NULL;

DROP TABLE STUDENT2;

CREATE SEQUENCE STUDENT2_SEQ
START WITH 1
INCREMENT BY 1;

--전공
CREATE TABLE MAJOR (
	NO NUMBER(4),
	MNUM VARCHAR2(10) NOT NULL,
	NAME VARCHAR2(20) NOT NULL
);
ALTER TABLE MAJOR ADD CONSTRAINT MAJOR_NO_PK PRIMARY KEY(NO);
ALTER TABLE MAJOR ADD CONSTRAINT MAJOR_MNUM_UK UNIQUE(MNUM);

SELECT * FROM MAJOR;

INSERT INTO MAJOR VALUES (MAJOR_SEQ.NEXTVAL, 01, '정보통신');
INSERT INTO MAJOR VALUES (MAJOR_SEQ.NEXTVAL, 02, '정보통신');
INSERT INTO MAJOR VALUES (MAJOR_SEQ.NEXTVAL, 03, '컴공');

CREATE SEQUENCE MAJOR_SEQ
START WITH 1
INCREMENT BY 1;

DROP SEQUENCE MAJOR_SEQ;
DROP TABLE MAJOR;

-- 수강과목들
CREATE TABLE CLASS (
	NO NUMBER(4), --PK 
	NAME VARCHAR2(20) NOT NULL,
	GRADE NUMBER(3,2) NOT NULL,
	MNUM VARCHAR2(10) --FK   --전공번호
);
ALTER TABLE CLASS ADD CONSTRAINT CLASS_NO_PK PRIMARY KEY(NO);
ALTER TABLE CLASS ADD CONSTRAINT CL_MJ_NUM_FK FOREIGN KEY(MNUM) REFERENCES MAJOR(MNUM) ON DELETE SET NULL;

CREATE SEQUENCE CALSS_SEQ
START WITH 1
INCREMENT BY 1;
	 commit;
     
SELECT *
FROM STUDENT INNER JOIN MAJOR INNER JOIN CALSS
ON MNUM;


SELECT *
FROM STUDENT S
INNER JOIN MAJOR M
ON S.MNUM = M.MNUM
INNER JOIN CLASS C
ON M.MNUM = C.MNUM;