CREATE TABLE CUSTOMER (
    USER_NO NUMBER,
    USER_ID VARCHAR2(50),
    USER_PWD VARCHAR2(50),
    USER_NAME VARCHAR(20)
);
INSERT INTO CUSTOMER VALUES (1, 'STER', '1234','MUN');

ALTER TABEL CUSTOMER ADD CONSTRAINTS USER_PK PRIMARY KEY (USER_NO);

create table class (
    class_no NUMBER,
    class_name VARCHAR2(50),
    class_title VARCHAR2(50),
    class_theme VARCHAR2(20)
);

INSERT INTO CLASS VALUES (1, '문정배사랑모임', '문사모','신앙');

create table meeting (
    USER_NO
    CLASS_NO
    CLASS_NAME
);

CREATE VIEW CLASS_CUSTOMER AS SELECT USER_NAME, CLASS_NO, CLASS_NAME, CLASS_TITLE, CLASS_THEME FROM CLASS, CUSTOMER WHERE CLASS_NO = 1;
SELECT * FROM CLASS_CUSTOMER;