--EMPLOYEES 를 복사해서 EMP03 으로 테이블 생성
CREATE TABLE EMP03
AS
SELECT * FROM EMPLOYEES;

SELECT * FROM EMP03;

ROLLBACK;

--모든사원의 부서번호를 30으로 설정
UPDATE EMP03 SET DEPARTMENT_ID = 30; 
--모든 사원의 급여를 10% 인상
UPDATE EMP03 SET SALARY = SALARY + (SALARY * 0.1);
--모든 사원의 입사일을 오늘로 수정
UPDATE EMP03 SET HIRE_DATE = SYSDATE;
--부서 번호가 10번인 사원의 부서번호를 30번으로 수정
UPDATE EMP03
SET DEPARTMENT_ID = 30
WHERE DEPARTMENT_ID = 10;

SELECT * FROM EMP03 WHERE DEPARTMENT_ID = 10;
--급여가 3000만원이상인 사람을 급여 10% 인상
UPDATE EMP03
SET SALARY = SALARY + (SALARY*0.1)
WHERE SALARY >= 3000;