--샘플문제
SELECT LAST_NAME, FIRST_NAME AS NAME, JOB_ID, SALARY
FROM EMPLOYEES
WHERE SALARY > (SELECT SALARY
                FROM EMPLOYEES
                WHERE UPPER(LAST_NAME) LIKE UPPER('TUCKER'));

--문제1번
SELECT LAST_NAME, FIRST_NAME AS NAME, SALARY, HIRE_DATE
FROM EMPLOYEES
WHERE (JOB_ID, SALARY) IN(SELECT JOB_ID, MIN(SALARY)
                          FROM EMPLOYEES
                          GROUP BY JOB_ID);


--문제2 (문정배식 풀이)
SELECT DISTINCT JOB_ID, FIRST_NAME AS NAME, LAST_NAME, SALARY, DEPARTMENT_ID
FROM EMPLOYEES EMP
WHERE SALARY > (SELECT AVG(SALARY)
                FROM EMPLOYEES
                WHERE DEPARTMENT_ID = EMP.DEPARTMENT_ID)
GROUP BY JOB_ID, FIRST_NAME, LAST_NAME, SALARY, DEPARTMENT_ID
ORDER BY JOB_ID ASC;
                    
--문제2 
SELECT LAST_NAME, FIRST_NAME AS NAME, SALARY, EMP.DEPARTMENT_ID, JOB_ID
FROM EMPLOYEES EMP
WHERE EMP.SALARY > (SELECT ROUND(AVG(SALARY))
                    FROM EMPLOYEES
                    WHERE DEPARTMENT_ID = EMP.DEPARTMENT_ID
                    GROUP BY DEPARTMENT_ID);
                  
                                                
--문제4번
SELECT LAST_NAME, FIRST_NAME AS NAME, JOB_ID, SALARY, DEPARTMENT_ID, 
(SELECT ROUND(AVG(SALARY))
 FROM EMPLOYEES 
 WHERE DEPARTMENT_ID = EMP.DEPARTMENT_ID) AS "DEPARTMENT AVG SALARY"
FROM EMPLOYEES EMP;

